### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by eoin**
- Use 2-legged oauth
- Tidied up serialization
- Added an example

### CODE REVIEW

**Comment by Najaf** [comment]
Currently in the labor ward, won't get a chance to look at this for a while!

**Comment by Najaf** [comment]
Quick question for you, I know its been a while since you sent these changes over but I wanted to ask if tests are running for you? 

Seem to be broken for me (on both my master and yours... :confused: ) so I'll need to spend some time getting them working before I can merge these changes.

**Comment by eoin** [comment]
I'm seeing all tests pass.

**Comment by Najaf** [comment]
@eoin hmm OK. I'll work on it and merge in as soon as I can get tests passing on my end.

**Comment by pellegrino** [comment]
They pass at my machine too, but in order to run them, i had to do a rake build to install that custom version of moo.rb and uninstall the previous one, as it uses Gem.datadir in several places, such as https://github.com/Najaf/moo.rb/blob/master/lib/moo/model/template.rb#L13. 

IMHO, it would be a great thing to refactor the tests to look for templates at a fixture path or something similar to that, instead of going to the actual gem installation dir.

**Comment by Najaf** [comment]
@eoin :cake:  for fixing those deprecation warnings.

**Comment by Najaf** [comment]
@pellegrino That sounds like a better way of doing things. I'll go ahead and open an issue for this.

**Pull request merged**
